apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "covideo-webserver"
  namespace: "default"
  labels:
    app: "covideo-webserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "covideo-webserver"
  template:
    metadata:
      labels:
        app: "covideo-webserver"
    spec:
      volumes:
        - name: google-app-credentials
          secret:
            secretName: google-app-credentials
      containers:
      - name: "covideo-webserver"
        image: "gcr.io/covideo/covideo:103031ef003524ad4529c7c458b044cd25171435"
        command: ["./webserver.sh"]
        volumeMounts:
          - name: google-app-credentials
            mountPath: /var/secrets/google  
        envFrom:
        - secretRef:
            name: django-settings
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "covideo-celeryworker"
  namespace: "default"
  labels:
    app: "covideo-celeryworker"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "covideo-celeryworker"
  template:
    metadata:
      labels:
        app: "covideo-celeryworker"
    spec:
      volumes:
        - name: google-app-credentials
          secret:
            secretName: google-app-credentials
      containers:
      - name: "covideo-celeryworker"
        image: "gcr.io/covideo/covideo:103031ef003524ad4529c7c458b044cd25171435"
        command: ["./celeryworker.sh"]
        volumeMounts:
          - name: google-app-credentials
            mountPath: /var/secrets/google  
        envFrom:
        - secretRef:
            name: django-settings