apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "covideo-webserver"
  namespace: "default"
  labels:
    app: "covideo-webserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "covideo-webserver"
  template:
    metadata:
      labels:
        app: "covideo-webserver"
    spec:
      containers:
      - name: "covideo-webserver"
        image: "gcr.io/covideo/covideo:6a9e825e3307b9d80ecd4696c93a5e911d46ae0a"
        command: ["./webserver.sh"]
        envFrom:
        - secretRef:
            name: django-settings
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "covideo-celeryworker"
  namespace: "default"
  labels:
    app: "covideo-celeryworker"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "covideo-celeryworker"
  template:
    metadata:
      labels:
        app: "covideo-celeryworker"
    spec:
      containers:
      - name: "covideo-celeryworker"
        image: "gcr.io/covideo/covideo:6a9e825e3307b9d80ecd4696c93a5e911d46ae0a"
        command: ["./celeryworker.sh"]
        envFrom:
        - secretRef:
            name: django-settings