apiVersion: v1
kind: Secret
metadata:
    name: django-settings
type: Opaque
stringData:
    ROOT_PATH: "https://covideo.org"
    DEBUG: "False"
    ALLOWED_HOSTS: "covideo.org,www.covideo.org"
    REDIS_CACHE_LOCATION: "redis://redis.default.svc.cluster.local/0"
    CELERY_BROKER_URL: "redis://redis.default.svc.cluster.local/1"
    DB_NAME: ""
    DB_USER: ""
    DB_PASSWORD: ""
    DB_HOST: ""
    EMAIL_HOST_USER: ""
    EMAIL_HOST_PASSWORD: ""
    EMAIL_HOST: ""
    DJANGO_SECRET_KEY: ""
    GS_BUCKET_NAME: "covideo-submissions"
    GOOGLE_APPLICATION_CREDENTIALS: "/var/secrets/google/key.json"
