# Generated by Django 2.2.11 on 2020-03-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
