# Generated by Django 3.0.4 on 2020-03-16 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
