# Generated by Django 2.2.11 on 2020-03-19 04:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200319_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Try to keep your video concise&mdash;aim for two minutes or less.', upload_to=core.models.video_upload_location),
        ),
    ]
