# Generated by Django 2.2.11 on 2020-04-04 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200321_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
